### ISSUE TITLE
某些用户的标识显示不全

### ISSUE THREAD

**Issue by zzzzy1985** [shenjia/saolei.net-2008#3]
如id18909的。标识里带M
我认为问题可能和下面的判断有关
if(result[number]=="S"){
        	number+=10;
        	while(result[number]!="M"){
	        	player+=result[number];
	        	number++;
	        }//标志读取完成
        }
        console.log('player:'+player);

补充 id18201 中文括号问题

**Comment by hgraceb** [comment]
1、标识不全问题已解决：将单纯的“S”、“M”等字母判断目标字符串开始与结束位置，改为采用charCodeAt()!=13判断终止位置。

2、中文括号问题已解决：截取初始Blob类型录像数据的用户标识部分，通过FileReader的readAsText方法转为gb2312编码格式。

**Comment by shenjia** [comment]
发pr

**Comment by zzzzy1985** [comment]
> 如id18909的。标识里带M
> 我认为问题可能和下面的判断有关
> if(result[number]=="S"){
> number+=10;
> while(result[number]!="M"){
> player+=result[number];
> number++;
> }//标志读取完成
> }
> console.log('player:'+player);
> 
> 补充 id18201 中文括号问题
